---
name: Jeesung Ahn
date: "`r format(Sys.time(), '%B, %Y')`"
position: Psychologist | Neuroscientist | Health Researcher
address: Department of Psychology, University of Pennsylvania, Philadelphia, PA, USA
email: jeesung@sas.upenn.edu
linkedin: jeesung-ahn
www: jeesung-ahn.github.io
github: jeesung-ahn
headcolor: "414141"
csl: apa-cv.csl # change this if you want to use other citation styles
output: 
  vitae::awesomecv:
    pandoc_args: ["--lua-filter=lua/strong.lua"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
#rmarkdown::pandoc_version()
```

# EDUCATION
```{r education}
tribble(
   ~degree, ~lab, ~ loc, ~ dates,  ~ details,
    "Ph.D. Candidate in Psychology, University of Pennsylvania", "Communication Neuroscience Lab (Advisor: Emily Falk, Ph.D.), Department of Psychology", "Aug. 2019 - expected May 2024", "Philadelphia, PA, USA", "Dissertation Committee: Drs. Anna Jenkins, Danielle Bassett, Emily Falk", 

  "M.A. in Psychology, University of Pennsylvania", "Communication Neuroscience Lab (Advisor: Emily Falk, Ph.D.), Department of Psychology", "Aug. 2019 - Aug. 2021", "Philadelphia, PA, USA", 
    "Thesis: Effects of message framing on neural responses to persuasive messaging and health behavior change",
  
  "M.S. in Cognitive Science and Engineering, Yonsei University", "
  Applied Brain Cognition Lab (Advisor: Sanghoon Han, Ph.D.), Interdepartmental Cognitive Science Program", "Mar. 2016 - Feb. 2018", "Seoul, South Korea", 
    "Thesis: Voxel-wise mapping of functional magnetic resonance imaging in impression formation (best thesis award)",
  
   "B.A. in Psychology & B.S. in Brain and Cognitive Sciences, Korea University", "Department of Psychology, College of Information and Communications", "Mar. 2011 - Aug. 2015", "Seoul, South Korea", NA,
  
   "Exchange Student Program, Macquarie University", "Department of Psychology", "July 2013 - Dec. 2013", "Sydney, Australia",  NA
) %>% 
  detailed_entries(lab, dates, degree, loc, details)
```


# ACADEMIC POSITIONS
```{r academic}

tribble(~ role, ~ company, ~ loc, ~ dates, ~ details,
        
"Doctoral Researcher", "Communication Neuroscience Lab, Department of Psychology, University of Pennsylvania", "Philadelphia, PA, USA", "Aug. 2019 – Present", list("Led 8+ multidisciplinary research projects in the fields of health psychology and neuroscience (research focus: health persuasion, health interventions, health behavior change, loneliness, social connections, brain networks, predictive modeling, machine learning)", "Collaborated with cross-functional teams of 70+ researchers from 10+ institutions; skilled at effectively visualizing and communicating complex scientific findings to diverse audiences", "Developed a lab-wide data processing pipeline for the streamlined analysis and visualization of complex multi-dimensional datasets (61TB), now actively used by global collaborators in 3+ countries"),

"Teaching Assistant", "Department of Psychology, University of Pennsylvania", "Philadelphia, PA, USA", "Jan. 2021 – Dec. 2021", list("Mentored 100+ undergraduates in developing effective study strategies during the challenging times of COVID-19", "Created evaluation tools, graded student essays, and provided constructive feedback", "Introduction to Experimental Psychology (Spring 2021, Rebecca Waller, Ph.D.; Fall 2021, Anna Jenkins, Ph.D.)"),

"Research Associate", "Applied Brain Cognition Lab, Yonsei University & Integrated Neurocognitive Functional Imaging Center, Yonsei University Severance Hospital", "Seoul, South Korea", "April 2015 – Mar. 2019", list("Designed and directed 7+ end-to-end behavioral and neuroimaging projects, resulting in 3 first-author publications, an award-winning Master’s thesis, and 6 international conference presentations", "Collaborated with cross-functional teams to develop a mobile application for treating social anxiety; conducted behavioral and neuroimaging experiments, in-depth interviews, and supervised machine learning analyses to evaluate user experience and clinical efficacy", "Mentored junior researchers in project management, neuroimaging analyses, data quality control, and MATLAB scripting"),

"Research Coordinator", "Brain Korea 21+, National Research Foundation of Korea", "Seoul, South Korea", "Jun. 2017 – Feb. 2018", list("Managed research and travel funds for Yonsei Applied Brain Cognition Lab, ensuring the smooth operation of multiple ongoing projects", "Constructed lab's annual review reports, highlighting significant achievements and future directions"),

"Research Coordinator", "Institute of Human Behavior, Yonsei University", "Seoul, South Korea", "Mar. 2016 – Aug. 2016", list("Organized academic social events (e.g., guest speaker series), building collaboration and community within Yonsei psychology department"),

"Research Assistant", "Laboratory of Social Decision Neuroscience, Korea University (Advisor: Hackjin Kim, Ph.D.)", "Seoul, South Korea", "Nov. 2014 – April 2015", list("Collected behavioral and neuroimaging data for an EEG hyperscanning experiment that investigated the neural mechanisms of teamwork")
) %>% detailed_entries(company, loc, role, dates, details)
```

# PUBLICATIONS
```{r}
bibliography_entries("publications.bib")
```

# WORKING PAPERS
```{r}
bibliography_entries("working_papers.bib")
```

##
```{r}
```

# PRESENTATIONS
## Invited Talks
```{r}
bibliography_entries("invited_talks.bib")
```

##
```{r}
```

## Conference Poster Presentations
```{r}
bibliography_entries("presentations.bib")
```


# VOLUNTEER ACTIVITIES & OUTREACH
```{r volunteer}

tribble(~ role, ~ company, ~ loc, ~ dates, ~ details,
"Vice President of Consulting", "Penn Graduate Consulting Club", "Philadelphia, PA, USA", "May 2023 – Present",list('Managed 6 project managers and 30+ analysts for successful execution of pro bono consulting projects','Established strong relationships with 5+ industry clients within the first 2 months of joining the board, doubling the number of secured pro bono projects compared to the previous term','Revamped marketing strategies to recruit talented staffs, increasing project member applications by 300\\%','Initiated structured training sessions for 30+ project managers and analysts on client expectations, high-quality deliverables, and presentations'), 

"Consultant", "Penn Biotech Group Healthcare Consulting", "Philadelphia, PA, USA", "Sept. 2022 – Jan. 2023", list("Presented weekly deliverables to the CEOs of a biotechnology start-up as part of an 11-person graduate research team", "Evaluated 200+ company profiles and clinical trial data, identifying 4 partnership opportunities with the highest synergistic potential", "Interviewed 10 key opinion leaders in healthcare (e.g., physicians), synthesizing their insights into clear recommendations on clinical trial design", "Recognized for exceptional contributions and recruited as Vice President of Consulting by Penn Graduate Consulting Club"), 

"Data Scientist", "Diversity and Equity Initiative in Mind Sciences", "Philadelphia, PA, USA", "Mar. 2022 – Mar. 2023", list("Designed online surveys to assess the effectiveness of education outreach programs","Visualized program outcomes using R (e.g., text-analyzed participant feedback) and delivered actionable insights to program organizers to enhance the overall participant experience"),

"Data Scientist", "Penn Data Science Group", "Philadelphia, PA, USA", "Feb. 2022 – May 2022", list("Synthesized air pollution and health data procured from 6 sources (100K+ data points) into an interactive heat map"),

"UX Research Consultant", "Team Quantumlabs (Start-Up)", "Seoul, South Korea", "Mar. 2016 – Feb. 2018", list("Directed research projects (A/B testing, surveys, lab experiments, and interviews) to assess user behavior and guide strategic product decisions for a novel neurostimulation device", 'Communicated award-winning scientific insights with cross-functional stakeholders (venture capital funders, designers, engineers, and clinicians), acquiring \\$100K+ in funding')

) %>% detailed_entries(company, loc, role, dates, details)

```

# INTERNSHIPS
```{r}
tribble(~ role, ~ company, ~ loc, ~ dates, ~ details,
"Healthcare Platform Data Strategy Intern", "Samsung Life Insurance", "Seoul, South Korea", "July 2023", list('Analyzed behavioral patterns and health conditions of Samsung healthcare app users (200K+ data points), driving substantial changes to the UI/UX design to reduce cognitive load and improve usability; led to a full-time return offer', 'Curated engaging wellbeing content to facilitate user acquisition and retention, presently integrated into the app'),

"Summer Intern", "KB Kookmin Bank", "Seoul, South Korea", "July 2014 – Aug. 2014", list("Received training in managing financial data and improving customer journeys at South Korea's largest commercial bank"),

"Student Intern", "Korean Cultural Center, Australia", "Sydney, Australia", "Sep. 2013 – Dec. 2013", list("Interfaced with customers visiting the center as a primary receptionist and provided translation services between English and Korean", "Monitored Korea-related media content broadcasted in Australia", "Organized cultural events, including K-pop dance and Korean speech contests")) %>% detailed_entries(company, loc, role, dates, details)

```

# SCHOLARSHIPS
```{r}
tribble(
  ~Year, ~Name, ~Institution, ~Supp, ~Amount,
  '2019 - Present', 'Penn Full-Ride Doctoral Fellowship ($400K)', 'School of Arts and Sciences, University of Pennsylvania', NA, NA,
  '2016 - 2017', 'Kwanjeong Full-Tuition Graudate Scholarship ($22K)', 'Kwanjeong Educational Foundation',NA,'http://en.ikef.or.kr',
  '2016 - 2017', 'Brain Korea 21+ Graduate Scholarship', 'National Research Foundation of Korea',NA,NA) %>%
  detailed_entries(
    where = Year,
    with = Name,
    what = Institution,
    why = Supp,
    when = Amount
  )
```


# HONORS & AWARDS
```{r awards, results='asis'}

tribble(
  ~name, ~company, ~loc, ~dates, ~details,
  "Comcast Applied AI Award", "Philly Codefest", NA, "2023", list("Managed a team of 2 software engineers to solve an AR/AI technology problem presented by Comcast; Came first place among 50+ teams", "Invited to present the AI solution to Comcast’s CTO at its headquarters"),
  
   "Top Poster Award", "Social Affective Neuroscience Society", NA, '2022', list('Presented findings at an invited talk titled "Brain responses to gain- and loss-framed messages differ, and interact with baseline physical activity, to predict later behaviors"; Awarded among 300+ attendees'),
  
   "Best Master's Thesis Award", "Yonsei University Graduate Group", NA,'2018',list('For the thesis titled "Voxel-wise mapping of functional magnetic resonance imaging in impression formation"; Awarded among 1K+ theses across 91 departments'),
  
     "Interdisciplinary Research Initiative Award, Grand Prize", "Institute of Convergence Science (ICONS)",NA,'2017',list('Collaborated with 3 electrical engineers to enhance medical image resolution using deep learning algorithms; Awarded \\$5K in research funding'),
  
  "Start-up Challenge Award", "Yonsei Enterprise Support Foundation", NA,'2016', list( 'Presented A/B test findings for a novel neurostimulation device developed by a start-up; Awarded \\$1K and office space; Led to \\$100K venture capital funding'),
  
    "Dean's Honors", "Department of Psychology, College of Information & Communications, Korea University", NA,'2011, 2013, 2014', list('For 5 out of 7 semesters; 2014, Fall Semester (GPA 4.25/4.5); 2014, Spring Semester (GPA 4.25/4.5); 2013, Spring Semester (GPA 4.0/4.5); 2011, Fall Semester (GPA 4.11/4.5); 2011, Spring Semester (GPA 4.37/4.5)')
  
  ) %>% detailed_entries(company, loc, name, dates, details)

cat("\n")
cat("\n")
cat("\n")

```